// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(AmdDBContext))]
    partial class AmdDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Auto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("AuctionId")
                        .HasColumnType("bigint");

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BuyDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("BuyerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuyingAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("CarName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarStatus")
                        .HasColumnType("int");

                    b.Property<int>("CarType")
                        .HasColumnType("int");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientBuyerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ColorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ContainerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreationUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DestinationId")
                        .HasColumnType("bigint");

                    b.Property<int>("DisplayStatus")
                        .HasColumnType("int");

                    b.Property<string>("Engine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("IsArchive")
                        .HasColumnType("tinyint");

                    b.Property<long>("LoadPortId")
                        .HasColumnType("bigint");

                    b.Property<string>("Lot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModificationUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaperStatus")
                        .HasColumnType("int");

                    b.Property<decimal?>("RemainingPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("VinNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("BrandId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("BuyingAccountId");

                    b.HasIndex("CityId");

                    b.HasIndex("ContainerId");

                    b.HasIndex("CreationUserId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("LoadPortId");

                    b.HasIndex("ModificationUserId");

                    b.ToTable("Autos");
                });

            modelBuilder.Entity("Entities.AutoImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Alt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AutoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreationUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Extintion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModificationUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewImageSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailImageSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutoId");

                    b.HasIndex("CreationUserId");

                    b.HasIndex("ModificationUserId");

                    b.ToTable("AutoImages");
                });

            modelBuilder.Entity("Entities.Container", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreationUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeparturePortId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DestinationId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("IsArchive")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModificationUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ShippingCompanyId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreationUserId");

                    b.HasIndex("DeparturePortId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("ModificationUserId");

                    b.HasIndex("ShippingCompanyId");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("Entities.ContainerImages", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Alt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ContainerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreationUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Extintion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModificationUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewImageSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailImageSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("CreationUserId");

                    b.HasIndex("ModificationUserId");

                    b.ToTable("ContainerImages");
                });

            modelBuilder.Entity("Entities.Lookup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lookups");
                });

            modelBuilder.Entity("Entities.LookupValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LookupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LookupId");

                    b.ToTable("LookupValues");
                });

            modelBuilder.Entity("Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("AutoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreationUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModificationUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AutoId");

                    b.HasIndex("CreationUserId");

                    b.HasIndex("ModificationUserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Entities.PaymentDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BuyType")
                        .HasColumnType("int");

                    b.Property<int>("CashType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentDetails");
                });

            modelBuilder.Entity("Entities.Resources", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Culture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("ActualPass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreationUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModificationUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreationUserId");

                    b.HasIndex("ModificationUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entities.Auto", b =>
                {
                    b.HasOne("Entities.LookupValue", "Auction")
                        .WithMany("AutoAuctions")
                        .HasForeignKey("AuctionId")
                        .IsRequired();

                    b.HasOne("Entities.LookupValue", "Brand")
                        .WithMany("AutoBrands")
                        .HasForeignKey("BrandId")
                        .IsRequired();

                    b.HasOne("Entities.User", "Buyer")
                        .WithMany("AutoBuyers")
                        .HasForeignKey("BuyerId");

                    b.HasOne("Entities.LookupValue", "BuyingAccount")
                        .WithMany("AutoBuyingAccounts")
                        .HasForeignKey("BuyingAccountId");

                    b.HasOne("Entities.LookupValue", "City")
                        .WithMany("AutoCities")
                        .HasForeignKey("CityId")
                        .IsRequired();

                    b.HasOne("Entities.Container", "Container")
                        .WithMany("Autos")
                        .HasForeignKey("ContainerId");

                    b.HasOne("Entities.User", "CreationUser")
                        .WithMany("AutoCreationUsers")
                        .HasForeignKey("CreationUserId");

                    b.HasOne("Entities.LookupValue", "Destination")
                        .WithMany("AutoDestinations")
                        .HasForeignKey("DestinationId")
                        .IsRequired();

                    b.HasOne("Entities.LookupValue", "LoadPort")
                        .WithMany("AutoLoadPorts")
                        .HasForeignKey("LoadPortId")
                        .IsRequired();

                    b.HasOne("Entities.User", "ModificationUser")
                        .WithMany("AutoModificationUsers")
                        .HasForeignKey("ModificationUserId");

                    b.Navigation("Auction");

                    b.Navigation("Brand");

                    b.Navigation("Buyer");

                    b.Navigation("BuyingAccount");

                    b.Navigation("City");

                    b.Navigation("Container");

                    b.Navigation("CreationUser");

                    b.Navigation("Destination");

                    b.Navigation("LoadPort");

                    b.Navigation("ModificationUser");
                });

            modelBuilder.Entity("Entities.AutoImage", b =>
                {
                    b.HasOne("Entities.Auto", "Auto")
                        .WithMany("Images")
                        .HasForeignKey("AutoId")
                        .IsRequired();

                    b.HasOne("Entities.User", "CreationUser")
                        .WithMany("AutoImageCreationUsers")
                        .HasForeignKey("CreationUserId");

                    b.HasOne("Entities.User", "ModificationUser")
                        .WithMany("AutoImageModificationUsers")
                        .HasForeignKey("ModificationUserId");

                    b.Navigation("Auto");

                    b.Navigation("CreationUser");

                    b.Navigation("ModificationUser");
                });

            modelBuilder.Entity("Entities.Container", b =>
                {
                    b.HasOne("Entities.User", "CreationUser")
                        .WithMany("ContainerCreationUsers")
                        .HasForeignKey("CreationUserId");

                    b.HasOne("Entities.LookupValue", "DeparturePort")
                        .WithMany("ContainerDeparturePorts")
                        .HasForeignKey("DeparturePortId");

                    b.HasOne("Entities.LookupValue", "Destination")
                        .WithMany("ContainerDestinations")
                        .HasForeignKey("DestinationId");

                    b.HasOne("Entities.User", "ModificationUser")
                        .WithMany("ContainerModificationUsers")
                        .HasForeignKey("ModificationUserId");

                    b.HasOne("Entities.LookupValue", "ShippingCompany")
                        .WithMany("ContainerShippingCompanies")
                        .HasForeignKey("ShippingCompanyId");

                    b.Navigation("CreationUser");

                    b.Navigation("DeparturePort");

                    b.Navigation("Destination");

                    b.Navigation("ModificationUser");

                    b.Navigation("ShippingCompany");
                });

            modelBuilder.Entity("Entities.ContainerImages", b =>
                {
                    b.HasOne("Entities.Container", "Container")
                        .WithMany("Images")
                        .HasForeignKey("ContainerId")
                        .IsRequired();

                    b.HasOne("Entities.User", "CreationUser")
                        .WithMany("ContainerImageCreationUsers")
                        .HasForeignKey("CreationUserId");

                    b.HasOne("Entities.User", "ModificationUser")
                        .WithMany("ContainerImageModificationUsers")
                        .HasForeignKey("ModificationUserId");

                    b.Navigation("Container");

                    b.Navigation("CreationUser");

                    b.Navigation("ModificationUser");
                });

            modelBuilder.Entity("Entities.LookupValue", b =>
                {
                    b.HasOne("Entities.Lookup", "Lookup")
                        .WithMany("LookupValues")
                        .HasForeignKey("LookupId")
                        .IsRequired();

                    b.Navigation("Lookup");
                });

            modelBuilder.Entity("Entities.Payment", b =>
                {
                    b.HasOne("Entities.Auto", "Auto")
                        .WithMany("Payments")
                        .HasForeignKey("AutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.User", "CreationUser")
                        .WithMany("PaymentCreationUsers")
                        .HasForeignKey("CreationUserId");

                    b.HasOne("Entities.User", "ModificationUser")
                        .WithMany("PaymentModificationUsers")
                        .HasForeignKey("ModificationUserId");

                    b.Navigation("Auto");

                    b.Navigation("CreationUser");

                    b.Navigation("ModificationUser");
                });

            modelBuilder.Entity("Entities.PaymentDetails", b =>
                {
                    b.HasOne("Entities.Payment", "Payment")
                        .WithMany("PaymentDetails")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.HasOne("Entities.User", "CreationUser")
                        .WithMany("InverseCreationUser")
                        .HasForeignKey("CreationUserId");

                    b.HasOne("Entities.User", "ModificationUser")
                        .WithMany()
                        .HasForeignKey("ModificationUserId");

                    b.Navigation("CreationUser");

                    b.Navigation("ModificationUser");
                });

            modelBuilder.Entity("Entities.Auto", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Entities.Container", b =>
                {
                    b.Navigation("Autos");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Entities.Lookup", b =>
                {
                    b.Navigation("LookupValues");
                });

            modelBuilder.Entity("Entities.LookupValue", b =>
                {
                    b.Navigation("AutoAuctions");

                    b.Navigation("AutoBrands");

                    b.Navigation("AutoBuyingAccounts");

                    b.Navigation("AutoCities");

                    b.Navigation("AutoDestinations");

                    b.Navigation("AutoLoadPorts");

                    b.Navigation("ContainerDeparturePorts");

                    b.Navigation("ContainerDestinations");

                    b.Navigation("ContainerShippingCompanies");
                });

            modelBuilder.Entity("Entities.Payment", b =>
                {
                    b.Navigation("PaymentDetails");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Navigation("AutoBuyers");

                    b.Navigation("AutoCreationUsers");

                    b.Navigation("AutoImageCreationUsers");

                    b.Navigation("AutoImageModificationUsers");

                    b.Navigation("AutoModificationUsers");

                    b.Navigation("ContainerCreationUsers");

                    b.Navigation("ContainerImageCreationUsers");

                    b.Navigation("ContainerImageModificationUsers");

                    b.Navigation("ContainerModificationUsers");

                    b.Navigation("InverseCreationUser");

                    b.Navigation("PaymentCreationUsers");

                    b.Navigation("PaymentModificationUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
